import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/navbar/Navbar";
import StyledComponentsRegistry from "./lib/AntdRegistry";
import Head from "next/head";
import { Providers } from "@/redux/provider";
import Footer from "./components/footer/Footer";
import { Open_Sans } from "next/font/google";
import { Roboto_Slab } from "next/font/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  // variable: "--bs-font-sans-serif",
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  // variable: "--bs-font-sans-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <Head>
        <title>Halal Travels Next.js</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="Halal Booking " content=""></meta>
        <meta
          name="description"
          content="Discover and book your dream vacations and travel experiences with ease. Explore a wide range of destinations and find the perfect accommodation and activities."
        ></meta>
        <meta
          name="keywords"
          content="booking, travel, vacations, reservations, accommodation, flights, hotels, activities, tours, explore, discover, adventure, holiday, trips"
        ></meta>
      </Head> */}
      <body className={robotoSlab.className}>
        <Providers>
          <StyledComponentsRegistry>
            <Navbar />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}
